package base_de_donnée;
import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.*;

public class Operateurs extends javax.swing.JFrame { 
    ResultSet rs;
    BDD db;

    public Operateurs() {
        db= new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB,new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
    }
    //fonction table
        public void table(){
            String a[]={"Matricule ", "Nom_et_prénom ", "Alias ", "Atelier "};
            rs = db.querySelect(a, "operateurs");
            Opérateurs_table.setModel(new ResultSetTableModel(rs));
        }
    void actualiser(){
        txt_Matricule.setText("");
        txt_Nom.setText("");
        txt_Alias.setText("");
        txt_Atelier.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Opérateurs_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Atelier = new javax.swing.JTextField();
        txt_Matricule = new javax.swing.JTextField();
        txt_Alias = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txt_Nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox<>();
        txt_rech = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(10000, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Opérateurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 0, 180, 44);

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));

        Opérateurs_table.setBackground(new java.awt.Color(204, 153, 255));
        Opérateurs_table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        Opérateurs_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opérateurs_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom_et_prénom", "Alias", "Atelier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Opérateurs_table.setShowHorizontalLines(true);
        Opérateurs_table.setShowVerticalLines(true);
        Opérateurs_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Opérateurs_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Opérateurs_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 60, 670, 110);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 360, 110, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 200, 110, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 200, 110, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(470, 200, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Atelier:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 400, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Recherche par Catégorie:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 310, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nom et Prénom:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 330, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alias:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 370, 100, 30);

        txt_Atelier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Atelier);
        txt_Atelier.setBounds(280, 410, 130, 23);

        txt_Matricule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Matricule);
        txt_Matricule.setBounds(280, 290, 130, 23);

        txt_Alias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Alias);
        txt_Alias.setBounds(280, 370, 130, 23);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 200, 110, 30);

        txt_Nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Nom);
        txt_Nom.setBounds(280, 330, 130, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Matricule:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 290, 60, 30);

        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricule", "Nom_et_prénom", "Alias", "Atelier" }));
        getContentPane().add(comrech);
        comrech.setBounds(670, 310, 123, 30);

        txt_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_rech);
        txt_rech.setBounds(670, 360, 100, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText(" Retour");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 0, 90, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Logo SAFRAN TUNISIE.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 450, 590, 180);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1350, 1680);

        setBounds(0, 0, 1365, 1687);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (txt_Matricule.getText().equals("") || txt_Nom.getText().equals("") || txt_Alias.getText().equals("") || txt_Atelier.getText().equals("")){
    JOptionPane.showMessageDialog (this, "SVP entrer les informations complétes");
} else {
    String[] colon = {"Matricule", "Nom_et_prénom", "Alias", "Atelier"};
    String[] inf = {txt_Matricule.getText(), txt_Nom.getText(), txt_Alias.getText(), txt_Atelier.getText()};
    System.out.println(db.queryInsert("operateurs", colon, inf));
    table();
    actualiser();
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(txt_Matricule.getText().equals("") || txt_Nom.getText().equals("") || txt_Alias.getText().equals("") || txt_Atelier.getText().equals("")){
         JOptionPane.showMessageDialog (this, "SVP entrer les informations complétes");   
        }else{ String[] colon = {"Matricule", "Nom_et_prénom", "Alias", "Atelier"};
               String[] inf = {txt_Matricule.getText(), txt_Nom.getText(), txt_Alias.getText(), txt_Atelier.getText()};
               String Matricule = String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 0));
               System.out.println(db.queryUpdate("operateurs", colon, inf,"Matricule='" + Matricule + "'"));
               table();
               actualiser();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Matricule= String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "est ce que vous êtes sûr que vous veuillez supprimer", "attention!!!",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
        {db.queryDelete("operateurs", "Matricule=" + Matricule);
   
        }else{
            return;
        }
        table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       actualiser(); table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txt_rech.getText().equals(""))// si le textfield de recherche est vide
       {
           JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
       } else{
           if (comrech.getSelectedItem().equals("Matricule")){
               rs = db.querySelectAll("operateurs", "Matricule LIKE '%" + txt_rech.getText() + "%' ");
               Opérateurs_table.setModel(new ResultSetTableModel(rs));
           } else if (comrech.getSelectedItem().equals("Nom_et_prénom")){
               rs = db.querySelectAll("operateurs", "Nom_et_prénom LIKE '%" + txt_rech.getText() + "%' ");
               Opérateurs_table.setModel(new ResultSetTableModel(rs));
           } else if (comrech.getSelectedItem().equals("Alias")){
               rs = db.querySelectAll("operateurs", "Alias LIKE '%" + txt_rech.getText() + "%' ");
               Opérateurs_table.setModel(new ResultSetTableModel(rs));
           }else if (comrech.getSelectedItem().equals("Atelier")){
               rs = db.querySelectAll("operateurs", "Atelier LIKE '%" + txt_rech.getText() + "%' ");
               Opérateurs_table.setModel(new ResultSetTableModel(rs));
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Opérateurs_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opérateurs_tableMouseClicked
        txt_Matricule.setText(String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 0)));
        txt_Nom.setText(String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 1)));
        txt_Alias.setText(String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 2)));
        txt_Atelier.setText(String.valueOf(Opérateurs_table.getValueAt(Opérateurs_table.getSelectedRow(), 3)));
    }//GEN-LAST:event_Opérateurs_tableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  Principale a=new Principale();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operateurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Opérateurs_table;
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Alias;
    private javax.swing.JTextField txt_Atelier;
    private javax.swing.JTextField txt_Matricule;
    private javax.swing.JTextField txt_Nom;
    private javax.swing.JTextField txt_rech;
    // End of variables declaration//GEN-END:variables
}
